name: Django Polls App CD

on:
  push:
    branches: main # 以下のbranchへのプッシュが実行されたジョブが始まる

jobs:

  Build-Test: # ビルドとテスト
    runs-on: ubuntu-latest
    env: # 仮想環境内の環境変数を定義
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.6
        uses: actions/setup-python@v3
        with:
          python-version: 3.6
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Code checker # コードのチェック
        continue-on-error: true
        run: |
          black --check polls
          flake8 polls mysite
          isort --check polls
      - name: Run Test
        run: |
          coverage run --include=polls/* --omit=polls/migrations/* manage.py test polls
      - name: Run Coverage report
        run: |
          coverage report
      - name: Run Migration check # データベーススキーマとモデルが一致しているか
        continue-on-error: true
        run: python3 manage.py makemigrations --check
      - name: Run Validate deploy # 安全にデプロイできるか検証
        run: python3 manage.py check --deploy

  Deploy: # アプリデプロイ
    runs-on: ubuntu-latest
    needs: Build-Test
    env:
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
    steps:
      - name: Deploy
        run: |
          printenv
          echo '----------'
          echo $SSH_PORT
          # ssh -p${SSH_PORT} ${SSH_USER}@${SSH_HOST} -i${SSH_KEY}
          echo date > date.txt
