name: Django CI/CD

on:
  push: # 以下のbranchへのプッシュが実行されたジョブが始まる
    branches: [ test ]
    # branches: [ $default-branch ]
  pull_request: # 設定するとジョブが重複してしまうのでNone
    types:
      - reopened
    branches: [ main ]
    # branches: [ $default-branch ]
  workflow_dispatch: # UIから手動で実行できるようになる

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  build-test-upload-artifact: # ビルドとテスト
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]
        # python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Test
        continue-on-error: true # test runが失敗しても、以降の処理が続行されるようにする
        run: coverage run --include=polls/* --omit=polls/migrations/* manage.py test polls
      - name: Run Coverage report
        run: |
          coverage report
          coverage html
      - name: Upload artifact # カバレッジレポートをアップロード
        uses: actions/upload-pages-artifact@v1
        with:
          path: htmlcov

  # デプロイ用のジョブ
  coverage-report:
    # if: "contains( github.base_ref , 'main')"
    # if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    needs: build-test-upload-artifact
    # 環境変数
    environment:
      name: github-pages
      url: ${{ steps.coverage.outputs.page_url }}
    steps:
      - name: Caverage to GitHub Pages # Pagesにデプロイ
        id: coverage
        uses: actions/deploy-pages@v1
